Assignment-4

UCS420 “Cognitive Computing” 

NumPy-Introduction-1 

Q.1 Write a program to create a NumPy 1D-array with 5 elements and perform basic 
operations like: 

a) Addition of 2 in all the element

In [17]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a+2)

[3 4 5 6 7]


b) Multiply 3 with all the elements 

In [19]:
print(a*3)

[ 3  6  9 12 15]


c) Divide every element by 2 

In [22]:
print(a/2)

[0.5 1.  1.5 2.  2.5]


Q.2 Questions on Basic NumPy Array:

a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])

In [26]:
b=np.array([1,2,3,6,4,5])
r_array=b[::-1]
print(r_array)

[5 4 6 3 2 1]


b) Find the most frequent value and their indice(s) in the following arrays:

i. x = np.array([1,2,3,4,5,1,2,1,1,1]) 

In [30]:
import numpy as np
x=np.array([1,2,3,4,5,1,2,1,1,1])
unique,counts=np.unique(x,return_counts=True)
most_frequent_value=unique[np.argmax(counts)]
indices=np.where(x==most_frequent_value)[0]
print("Most Frequent Value:",most_frequent_value)
print("Indices:",indices)

Most Frequent Value: 1
Indices: [0 5 7 8 9]


ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [33]:
import numpy as np
y=np.array([1,1,1,2,3,4,2,4,3,3])
unique,counts=np.unique(y,return_counts=True)
most_frequent_value=unique[np.argmax(counts)]
indices=np.where(y==most_frequent_value)[0]
print("Most Frequent Value:",most_frequent_value)
print("Indices:",indices)

Most Frequent Value: 1
Indices: [0 1 2]


Q.3 For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access 
elements using row and column indices as follows:

a) Access 1st row, 2nd column  

In [37]:
arr=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(arr[0][1])

20


b) Access 3rd row, 1st column 

In [40]:
print(arr[2][0])

70


Q.4 Write program to create an 1-D NumPy array named <<Your Name>> with evenly 
spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array, 
shape, total elements, the data type of each element and total number of bytes consumed 
by the array. Find the transpose of this array using reshape() attribute. Can we do the same 
with T attribute? 

In [43]:
Aniket=np.linspace(10,100,25)
print(Aniket)
print(np.ndim(Aniket))
print(np.shape(Aniket))
print(len(Aniket))
print(Aniket.dtype)
print(Aniket.nbytes)
print(Aniket.reshape(1,25))
print(Aniket.T)
print(np.shape(Aniket))

[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
1
(25,)
25
float64
200
[[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
   47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
   85.    88.75  92.5   96.25 100.  ]]
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
(25,)


Q5. Create a 2-D Array of three rows and four columns, named ucs420_<your_name>> 
with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean, 
median, max, min, unique elements. Reshape the array to four rows and three columns and 
name it as reshaped_ ucs420_<your_name>>. Resize the array to two rows and three 
columns and name it as resized_ ucs420_<your_name>>.

In [46]:
ucs420_aniket=np.array([[10,20,30,40],[50,60,70,80],[90,15,20,35]])
m=np.mean(ucs420_aniket)
print("Mean:",m)
x=np.median(ucs420_aniket)
print("Median:",x)
y=np.max(ucs420_aniket)
print("Max:",y)
z=np.min(ucs420_aniket)
print("Min:",z)
reshaped_ucs420_aniket=ucs420_aniket.reshape(4,3)
print(reshaped_ucs420_aniket)
resized_ucs420_aniket=np.resize(reshaped_ucs420_aniket,(2,3))
print(ucs420_aniket)

Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
